include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - third_party/**

linter:
  rules:
    avoid_positional_boolean_parameters: false
    public_member_api_docs: false
    prefer_double_quotes : false
    prefer_single_quotes : false
